name = "scrabble-roto-sync"
main = "worker.js"
compatibility_date = "2024-01-01"

# Non-secret environment variables
[vars]
EVENT_ID = "1"

# Secrets - set these via dashboard or wrangler secret command
# SUPABASE_URL = "set via: wrangler secret put SUPABASE_URL"
# SUPABASE_SERVICE_ROLE_KEY = "set via: wrangler secret put SUPABASE_SERVICE_ROLE_KEY"

# Cron trigger to run sync every 4 hours
[triggers]
crons = ["0 */4 * * *"]

# Optional: Custom domain for the worker
# [env.production]
# routes = [
#   { pattern = "sync.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
